---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: Execute direct linux command
    command: hostname -f
    register: myresult

  - name:  i want to display my first task result
    debug:
      msg: "{{myresult}}"

  - name: Install git
    apt:
      name: git
      state: present
    when: myresult.stderr==""

  - name: Install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr_lines==[]