---
- hosts: 10.0.0.5
  becoome: yes
  tasks:
  - name: Install git
    apt:
      name: git
      state: present
  
  - name: Install tree
    apt:
      name: tree
      stte: present

  - name: Install wget
    apt:
      name: wget
      state: present