---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: I want to install webserver
    apt:
      name: apache2
      state: present
    notify: Restartwebserver

  - name: Copy static file from master to Nodes
    copy:
      src: mystaticfile
      dest: /home/karthik/

  - name: Copy my dyno file from master to Nodes
    template:
      src: mydynofile.j2
      dest: /var/www/html/index.html
    notify: Restartwebserver

  - name: Download Internet files into node side 
    get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer-host_amd64.deb
      dest: /home/karthik/teamviewer-host_amd64.deb
      force_basic_auth: yes
  handlers:
  - name: Restartwebserver
    service:
      name: apache2
      state: restarted