---
- name: Download tomcat tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/karthik/apache-tomcat-10.0.20.tar.gz
  
- name: Create tomcat folder
  file:
    path: /opt/tomcat
    state: directory
  
- name: I want to extract tar file into tomcat folder
  command:
    cmd: sudo tar xzvf /home/karthik/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE
    